# **Education**

- Master of Public Health, Biostatistics (2018 – Present)
Columbia University Mailman School of Public Health, New York, New York

- Bachelor of Science, Biology (2010 – 2014)
McGill University, Montreal, Quebec 
  - Minor in Anthropology

# **Work Experience** 
Interventional Cardiovascular Research and Clinical Trials at the Icahn School of Medicine at Mount Sinai, New York, New York:

  - Senior Clinical Research Associate (August 2018 - Present)

  - Clinical Research Associate (July 2016 - August 2018)

  - Clinical Research Assistant II (October 2015 – July 2016)

  - Volunteer (July 2015 – October 2015)

## **Work Responsibilities:**
-	Oversees the drug distribution and management, as well as the organization and maintenance the electronic data capture system maintenance for the TWILIGHT Study - an international, multi-center, prospective, double-blinded, randomized dual-arm study.

-	Assists in site activation and management for both domestic and international sites.

-	Supervises multiple international CROs.

-	Assisted in the submission and renewals of domestic and international regulatory applications.

-	Designs and provides study materials for efficient and effective project management. 

-	Collaborates daily in a dynamic work environment to ensure seamless trial operations.

